spring:
  config:
    import: classpath:/env.yml
    activate:
      on-profile: prod

  data:
    redis:
      host: ${db.redis.host}
      port: ${db.redis.port}
      password: ${db.redis.password}

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${db.prod.url}
    username: ${db.prod.username}
    password: ${db.prod.password}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false

jwt:
  secretKey: ${jwt.secret}
  prefix: ${jwt.prefix}
  accessTokenExp: ${jwt.access-token-exp}
  refreshTokenExp: ${jwt.refresh-token-exp}

oauth:
  google:
    client-id: ${oauth.google.client-id}
    client-secret: ${oauth.google.client-secret}
    grant_type: authorization_code
    redirect_uri: ${oauth.google.redirect-uri-prod}